services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: genagents_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: genagents_api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG:-false}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./agent_bank:/app/agent_bank
      - ./interview_questions.json:/app/interview_questions.json
      - ./interview_questions_short.json:/app/interview_questions_short.json
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn interview_api:app --host 0.0.0.0 --port 8000 --reload

  # Next.js Frontend
  frontend:
    build:
      context: ./interview-webapp
      dockerfile: Dockerfile
    container_name: genagents_frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: