services:
  - type: web
    name: interview-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONPATH
        value: /opt/render/project/src